open-rpc/spec

README.md

fix: use OpenRPC over OPENRPC

---

README.md

fix: remove datatypes and defer to json schema spec

---

README.md

fixes #50, fixes #47, fixes #44, fixes #33, fixes #48

fix: method over operation

---

README.md

fix: always use examples as array

---

README.md

fix: lowercase error field names

---

README.md

fix: remove comment about organization

---

README.md

fix: server needs name

---

README.md

fix: remove header a wrappers

---

README.md

fix: use Github Flavored Markdown

---

.circleci/config.yml

feat: add empty circle ci config

---

.circleci/config.yml
.gitignore
package-lock.json
package.json

As discussed in #74 #75 #78 
The build currently doesn't pass because of the link errors in `README.md`. These can be fixed in subsequent PRs.
`mdv` [warnings](https://github.com/Mermade/mdv#warnings) can later be enabled if necessary, and a build badge added to the `README`.
The `package.json` setup could (possibly with some changes) be used for publishing artifacts such as a JSON schema for the spec.

feat: add mdv checking to circleci

---

README.md

fix: fix ci

---

README.md

feat: add service description to the spec

---

README.md

feat: add examples mapping object

---

README.md

fix: unescaped by-position

---

README.md

fix: add required to errorObject fields

---

README.md

fix(contentDescriptor): name is required

---

README.md

fix(components): add tagObject

---

README.md

fix(serverObject): add summary

---

README.md

fix: dont center examplePairingObject

---

README.md

fix(components): add examplePairingObjects

---

docs/index.html

fixes #124 
once merged, lets delete the gh-pages branch and swap things

feat: gh pages from master

---

README.md

fix: add name and summary to Link Object

---

README.md

fix: schema required on contentDescriptorObject

---

README.md

fix: define JSON String templating language for template strings

---

README.md

fix: remove examples from spec

---

.markdownlint.json
README.md
package-lock.json
package.json

fix: add markdownlint

---

README.md

fix: dont use method text in content descriptor

---

bin/build.ghpages.sh

feat: add link for latest version of spec

---

spec.md

fix: Change type of MethodObject.name to string

---

spec.md

fixes #270
rel https://github.com/open-rpc/meta-schema/pull/217

fix: default paramStructure to either

---

FAQ.md

Move FAQ.md from the wiki tab into the repository.
fixes #283
Should remove/disable Wiki once merged.

fix: update FAQ and add to repo

---

spec.md

fix: remove oneOf

---

.releaserc

fixes #292
One problem is that GH is messed up today. But that aside, there is still the following error in circle:

fix: re-order release perparation steps

---

spec.md

fix: dont point to latest json schema
